environment: staging

database:
  host: staging-db.myapp.com
  name: myapp_staging

api:
  api_endpoint: https://api-staging.myapp.com
  log_level: info 

features:
  enable_experimental: true # Test new features with almost-real data
  payment_test_mode: true # Still no real money